### ISSUE TITLE
How and Where to set them

### ISSUE THREAD

**Issue by Tharun-tharun** [shanayghag/ML-Projects#1]
Thank you. Well done!

**Comment by Tharun-tharun** [comment]
please guide me through step by step process

**Comment by shanayghag** [comment]
Hi Tharun,
I think the following link will help you.
https://www.geeksforgeeks.org/how-to-upload-project-on-github-from-google-colab/

**Comment by Tharun-tharun** [comment]
Lots of thanks to you.
